if __name__ == '__main__':
    Ps = int(input("enter the Ps: "))
    Gs = int(input("enter the Gs: "))
    print('Value of Ps is : %d'%(Ps))
    print('Value of Gs is : %d'%(Gs))
    g = int(input("Enter the g: "))
    print('Private Key g is: %d'%(g))
    p = int(pow(Gs,g,Ps))
    h = int(input("Enter the h: "))
    print('Private Key h is : %d'%(h))
    q = int(pow(Gs,h,Ps))
    K_A = int(pow(q,g,Ps))
    K_B = int(pow(p,h,Ps))
    print('Alice\'s Secret key is : %d'%(K_A))
    print('Bob\'s Secret key is : %d'%(K_B))
